Repository istio-ecosystem/authservice, pull requests merged in 2019-10, with the labels that each got.

#25 The check()'s request has no scheme, so don't rely on it
  src/filters/oidc/oidc_filter.cc
  test/filters/oidc/oidc_filter_test.cc
Labels: cla: yes, lgtm, size/XS

#20 Add the prefix "Bearer " to the Authorization header
  src/filters/oidc/oidc_filter.cc
  test/filters/oidc/oidc_filter_test.cc
Labels: cla: yes, lgtm, size/XS

#22 New dockerfile for system-independent compilation
  Makefile
  build/Dockerfile.interactive-compile-environment
Labels: cla: yes, lgtm, size/S

#27 Configuration via file
  .gitignore
  Makefile
  build/Dockerfile.builder
  config/BUILD
  config/common/BUILD
  config/common/config.proto
  config/config.proto
  config/oidc/BUILD
  config/oidc/config.proto
  docker-compose.yml
  run/envoy/envoy.yaml
  src/common/http/BUILD
  src/common/http/headers.h
  src/common/http/http.cc
  src/common/http/http.h
  src/common/session/token_encryptor.cc
  src/common/utilities/random.h
  src/config/BUILD
  src/config/getconfig.cc
  src/config/getconfig.h
  src/filters/filter.h
  src/filters/oidc/BUILD
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/oidc_idp_configuration.cc
  src/filters/oidc/oidc_idp_configuration.h
  src/filters/oidc/state_cookie_codec.cc
  src/filters/oidc/state_cookie_codec.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  src/main/auth-server.cc
  src/service/BUILD
  src/service/serviceimpl.cc
  src/service/serviceimpl.h
  test/common/http/http_test.cc
  test/common/http/mocks.h
  test/filters/oidc/BUILD
  test/filters/oidc/mocks.h
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/oidc_idp_configuration_test.cc
  test/filters/oidc/token_response_test.cc
  test/service/BUILD
  test/service/data/config.json
  test/service/serviceimpl_test.cc
Labels: cla: yes, size/XL

#23 Fix the "docker" target in the Makefile to use Dockerfile.builder
  .bazelrc
  .gitignore
  Makefile
Labels: cla: yes, lgtm, size/S

#26 Fix bug where state and nonce were wrong in query params
  src/common/http/http.cc
  test/common/http/http_test.cc
  test/filters/oidc/oidc_filter_test.cc
Labels: cla: yes, size/S

#39 Additional config 4
  build/Dockerfile.builder
  config/config.proto
  config/oidc/config.proto
  src/config/BUILD
  src/config/getconfig.cc
  src/config/getconfig.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/token_response.h
  src/main/auth-server.cc
  src/service/serviceimpl.cc
  src/service/serviceimpl.h
  test/config/BUILD
  test/config/getconfig_test.cc
  test/filters/oidc/oidc_filter_test.cc
  test/fixtures/BUILD
  test/fixtures/invalid-config-with-intermediate-nodes.json
  test/fixtures/invalid-config.json
  test/fixtures/valid-config.json
  test/service/BUILD
  test/service/serviceimpl_test.cc
Labels: cla: yes, size/XL

#30 Sample instructions
  README.md
  bookinfo-example/README.md
  bookinfo-example/config/authservice-configmap-template.yaml
  bookinfo-example/config/bookinfo-authn-policy-template.yaml
  bookinfo-example/config/bookinfo-gateway.yaml
  bookinfo-example/config/bookinfo-with-authservice.yaml
  bookinfo-example/config/external-authz-envoyfilter-sidecar.yaml
  bookinfo-example/scripts/download-istio-1.3.sh
  bookinfo-example/scripts/generate-self-signed-certs-for-ingress-gateway.sh
  bookinfo-example/scripts/install-istio.sh
Labels: cla: yes, size/XL

#42 13 select token
  WORKSPACE
  bookinfo-example/README.md
  bookinfo-example/config/authservice-configmap-template.yaml
  config/BUILD
  config/common/BUILD
  config/common/config.proto
  config/config.proto
  config/oidc/BUILD
  config/oidc/config.proto
  src/config/getconfig.cc
  src/config/getconfig.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  src/main/auth-server.cc
  src/service/serviceimpl.cc
  test/common/http/http_test.cc
  test/config/getconfig_test.cc
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/token_response_test.cc
  test/fixtures/valid-config.json
  test/service/serviceimpl_test.cc
Labels: cla: yes, lgtm, size/XL

#48 Add test for pull requests through Github Actions
  .github/workflows/pr.yml
  Makefile
Labels: cla: yes, size/S

#46 All namespaces and headers that use transparent_auth to authservice
  src/common/http/headers.h
  src/common/http/http.cc
  src/common/http/http.h
  src/common/session/gcm_encryptor.cc
  src/common/session/gcm_encryptor.h
  src/common/session/hkdf_deriver.cc
  src/common/session/hkdf_deriver.h
  src/common/session/token_encryptor.cc
  src/common/session/token_encryptor.h
  src/common/utilities/random.cc
  src/common/utilities/random.h
  src/config/getconfig.cc
  src/config/getconfig.h
  src/filters/filter.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/state_cookie_codec.cc
  src/filters/oidc/state_cookie_codec.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  src/filters/pipe.cc
  src/filters/pipe.h
  src/main/auth-server.cc
  src/service/serviceimpl.cc
  src/service/serviceimpl.h
  test/common/http/http_test.cc
  test/common/http/mocks.h
  test/common/session/gcm_encryptor_test.cc
  test/common/session/hkdf_deriver_test.cc
  test/common/session/mocks.h
  test/common/session/token_encryptor_test.cc
  test/common/utilities/random_test.cc
  test/config/getconfig_test.cc
  test/filters/oidc/mocks.h
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/state_cookie_codec_test.cc
  test/filters/oidc/token_response_test.cc
  test/filters/pipe_test.cc
  test/service/serviceimpl_test.cc
Labels: cla: yes, lgtm, size/L

#44 use correct cluster type
  bookinfo-example/config/external-authz-envoyfilter-sidecar.yaml
Labels: cla: yes, size/XS

#47 33 fix todos
  Makefile
  WORKSPACE
  build/Dockerfile.builder
  build/install-bazel.sh
  config/oidc/config.proto
  docker-compose.yml
  src/common/http/headers.h
  src/common/session/token_encryptor.cc
  src/filters/oidc/BUILD
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  test/config/getconfig_test.cc
  test/filters/oidc/mocks.h
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/token_response_test.cc
  test/fixtures/valid-config.json
Labels: cla: yes, lgtm, size/L

#52 Fix invalid OWNERS file.
  OWNERS
Labels: cla: yes, size/XS
