Repository istio-ecosystem/authservice, pull requests merged in 2019-11, with the labels that each got.

#51 multiple idp support
  Makefile
  bookinfo-example/README.md
  bookinfo-example/config/authservice-configmap-template.yaml
  config/common/config.proto
  config/config.proto
  config/oidc/config.proto
  docker-compose.yml
  docs/README.md
  src/config/getconfig.cc
  src/config/getconfig.h
  src/filters/BUILD
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/main/BUILD
  src/main/auth-server.cc
  src/service/BUILD
  src/service/serviceimpl.cc
  src/service/serviceimpl.h
  test/config/getconfig_test.cc
  test/filters/BUILD
  test/filters/filter_chain_test.cc
  test/fixtures/valid-config.json
  test/service/BUILD
  test/service/serviceimpl_test.cc
Labels: cla: yes, lgtm, size/XL

#53 Issue35 async requests
  .dockerignore
  .gitignore
  Makefile
  WORKSPACE
  bazel/BUILD.boost
  bazel/boost.bzl
  build/Dockerfile.builder
  build/Dockerfile.runner
  config/config.proto
  docker-compose.yml
  run/envoy/.gitignore
  src/common/http/BUILD
  src/common/http/http.cc
  src/common/http/http.h
  src/config/BUILD
  src/config/get_config.cc
  src/config/get_config.h
  src/filters/BUILD
  src/filters/filter.cc
  src/filters/filter.h
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/filters/oidc/BUILD
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/pipe.cc
  src/filters/pipe.h
  src/main/BUILD
  src/main/auth-server.cc
  src/main/auth_server.cc
  src/service/BUILD
  src/service/async_service_impl.cc
  src/service/async_service_impl.h
  src/service/service_impl.cc
  src/service/service_impl.h
  test/common/http/mocks.h
  test/config/BUILD
  test/config/getconfig_test.cc
  test/filters/oidc/oidc_filter_test.cc
  test/fixtures/BUILD
  test/fixtures/valid-config.json
  test/service/BUILD
  test/service/serviceimpl_test.cc
Labels: cla: yes, lgtm, size/XXL

#55 Enable TLS peer verification and add CA root certificates to Docker images
  build/Dockerfile.builder
  build/Dockerfile.runner
  src/common/http/http.cc
Labels: cla: yes, lgtm, size/S
