Repository istio-ecosystem/authservice, pull requests merged in 2020-03, with the labels that each got.

#72 Allow Post to trust a provided CA on requests to OIDC token endpoint
  config/oidc/config.proto
  docs/README.md
  src/common/http/http.cc
  src/common/http/http.h
  src/filters/oidc/oidc_filter.cc
  test/common/http/mocks.h
  test/filters/oidc/oidc_filter_test.cc
  test/fixtures/valid-config.json
Labels: cla: yes, lgtm, size/L

#74 Issue 62 ignore public paths
  config/config.proto
  config/oidc/config.proto
  docs/README.md
  src/common/utilities/BUILD
  src/common/utilities/trigger_rules.cc
  src/common/utilities/trigger_rules.h
  src/service/BUILD
  src/service/service_impl.cc
  src/service/service_impl.h
  test/common/utilities/BUILD
  test/common/utilities/trigger_rules_test.cc
  test/config/getconfig_test.cc
  test/fixtures/valid-config.json
  test/service/service_impl_test.cc
Labels: cla: yes, lgtm, size/L

#76 Improve readme
  README.md
  bookinfo-example/README.md
  bookinfo-example/config/bookinfo-gateway.yaml
  bookinfo-example/config/bookinfo-with-authservice-template.yaml
Labels: cla: yes, lgtm, size/M

#77 Issue60 config uris as strings 2
  bookinfo-example/config/authservice-configmap-template-for-authn-and-authz.yaml
  bookinfo-example/config/authservice-configmap-template-for-authn.yaml
  config/common/BUILD
  config/common/config.proto
  config/oidc/BUILD
  config/oidc/config.proto
  docs/README.md
  src/common/http/BUILD
  src/common/http/http.cc
  src/common/http/http.h
  src/config/BUILD
  src/config/get_config.cc
  src/config/get_config.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/service/service_impl.cc
  test/common/http/BUILD
  test/common/http/http_test.cc
  test/common/http/mocks.h
  test/config/BUILD
  test/config/getconfig_test.cc
  test/filters/oidc/oidc_filter_test.cc
  test/fixtures/BUILD
  test/fixtures/invalid-config-with-intermediate-nodes.json
  test/fixtures/invalid-config.json
  test/fixtures/valid-config.json
  test/shared/BUILD
  test/shared/assertions.h
Labels: cla: yes, size/XXL

#81 Always ignore stream_truncated errors from async_shutdown
  src/common/http/http.cc
Labels: cla: yes, lgtm, size/S

#82 Support sending requests through a web proxy
  config/oidc/config.proto
  src/common/http/http.cc
  src/common/http/http.h
  src/config/get_config.cc
  src/filters/oidc/oidc_filter.cc
  test/common/http/http_test.cc
  test/common/http/mocks.h
  test/config/getconfig_test.cc
  test/filters/oidc/oidc_filter_test.cc
  test/fixtures/valid-config.json
Labels: cla: yes, lgtm, size/L
