Repository istio-ecosystem/authservice, pull requests merged in 2021-11, with the labels that each got.

#187 Remove the authentication based on "Authorization: <id-token>".
  src/filters/oidc/BUILD
  src/filters/oidc/authorization_state.h
  src/filters/oidc/jwt_verifier.cc
  src/filters/oidc/jwt_verifier.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  test/filters/oidc/BUILD
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/token_response_test.cc
  test/service/healthcheck_http_server_test.cc
Labels: cla: yes, lgtm, size/L, approved

#191 Fix the authservice httpGet probe config and use jwks_uri.
  bookinfo-example/authservice/templates/config.yaml
  bookinfo-example/authservice/templates/deployment.yaml
Labels: size/S, approved

#193 Add clang.bazelrc setup from envoy.
  .bazelrc
  .gitignore
  README.md
  bazel/BUILD.boost
  bazel/boost.bzl
  bazel/setup_clang.sh
Labels: size/M, lgtm, approved

#194 Add FIPS build option for the authservice.
  README.md
  WORKSPACE
  bazel/repositories.bzl
  src/common/http/BUILD
  src/common/utilities/BUILD
Labels: size/S, lgtm, approved

#196 Make it possible to run clang/fips build in container.
  Makefile
  README.md
  build/Dockerfile.build
  build/Dockerfile.builder
Labels: size/M, lgtm, approved
