Repository istio-ecosystem/authservice, pull requests merged in 2021-10, with the labels that each got.

#160 fix invalid loglevel on OIDC filter
  src/filters/oidc/token_response.cc
  test/filters/oidc/jwks_resolver_test.cc
Labels: cla: yes, size/S, lgtm, approved

#165 filter and session store abstraction and filter chain refactor
  src/filters/BUILD
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/filters/filter_factory.h
  src/filters/mock/BUILD
  src/filters/mock/mock_filter.cc
  src/filters/mock/mock_filter.h
  src/filters/oidc/BUILD
  src/filters/oidc/in_memory_session_store.cc
  src/filters/oidc/in_memory_session_store.h
  src/filters/oidc/jwks_resolver.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/redis_session_store.cc
  src/filters/oidc/redis_session_store.h
  src/filters/oidc/session_store.h
  src/filters/oidc/session_store_factory.h
Labels: cla: yes, lgtm, size/L, approved

#169 replace numbered mock helper with un-numbered one
  test/common/http/mocks.h
  test/common/utilities/mocks.h
  test/filters/oidc/mocks.h
Labels: cla: yes, lgtm, size/L, approved

#167 fix OOM while processing gRPC completion state
  src/service/async_service_impl.cc
  src/service/async_service_impl.h
Labels: cla: yes, size/S

#178 Update document of how to perform load test.
  test/perf/README.md
  test/perf/authservice-cookie-capture.png
  test/perf/authservice-perf-gcp.png
Labels: cla: yes, size/M, approved
