Repository istio-ecosystem/authservice, pull requests merged in 2021-02, with the labels that each got.

#134 Add lizan and zack to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#130 auth message V3 migration and backward compatibility
  .bazelrc
  .bazelversion
  .dockerignore
  .github/workflows/commit.yml
  .github/workflows/pr.yml
  .github/workflows/workflow.yml
  .gitignore
  BUILD
  Makefile
  WORKSPACE
  bazel/hiredis.BUILD
  bazel/redis_plus_plus.BUILD
  bazel/repositories.bzl
  build/Dockerfile.builder
  build/Dockerfile.runner
  build/install-bazel.sh
  docker-compose.yml
  run/envoy/envoy.yaml
  src/config/get_config.cc
  src/filters/BUILD
  src/filters/filter.h
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/pipe.cc
  src/filters/pipe.h
  src/main/BUILD
  src/main/auth_server.cc
  src/service/BUILD
  src/service/async_service_impl.cc
  src/service/async_service_impl.h
  test/common/utilities/trigger_rules_test.cc
  test/filters/BUILD
  test/filters/filter_chain_test.cc
  test/filters/oidc/BUILD
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/token_response_test.cc
  test/service/async_service_impl_test.cc
Labels: approved, cla: yes, lgtm, size/XXL

#133 Add global filter chain configuration API part 1
  config/config.proto
Labels: approved, cla: yes, lgtm, size/S

#135 add clang-format
  .clang-format
  .github/workflows/workflow.yml
  .gitignore
  Makefile
  src/common/http/http.cc
  src/common/http/http.h
  src/common/session/session_string_generator.cc
  src/common/session/session_string_generator.h
  src/common/utilities/random.cc
  src/common/utilities/random.h
  src/common/utilities/synchronized.h
  src/common/utilities/time_service.cc
  src/common/utilities/time_service.h
  src/common/utilities/trigger_rules.cc
  src/common/utilities/trigger_rules.h
  src/config/get_config.cc
  src/filters/filter.h
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/filters/oidc/authorization_state.cc
  src/filters/oidc/authorization_state.h
  src/filters/oidc/in_memory_session_store.cc
  src/filters/oidc/in_memory_session_store.h
  src/filters/oidc/oidc_filter.cc
  src/filters/oidc/oidc_filter.h
  src/filters/oidc/redis_retry_wrapper.cc
  src/filters/oidc/redis_retry_wrapper.h
  src/filters/oidc/redis_session_store.cc
  src/filters/oidc/redis_session_store.h
  src/filters/oidc/redis_wrapper.cc
  src/filters/oidc/redis_wrapper.h
  src/filters/oidc/session_store.h
  src/filters/oidc/token_response.cc
  src/filters/oidc/token_response.h
  src/filters/pipe.cc
  src/filters/pipe.h
  src/service/async_service_impl.cc
  src/service/async_service_impl.h
  test/common/http/http_test.cc
  test/common/http/mocks.h
  test/common/session/mocks.h
  test/common/session/session_string_generator_test.cc
  test/common/utilities/mocks.h
  test/common/utilities/random_test.cc
  test/common/utilities/trigger_rules_test.cc
  test/config/getconfig_test.cc
  test/filters/filter_chain_test.cc
  test/filters/oidc/in_memory_session_store_test.cc
  test/filters/oidc/mocks.h
  test/filters/oidc/oidc_filter_test.cc
  test/filters/oidc/redis_retry_wrapper_test.cc
  test/filters/oidc/redis_session_store_test.cc
  test/filters/oidc/token_response_test.cc
  test/filters/pipe_test.cc
  test/service/async_service_impl_test.cc
  test/shared/assertions.h
Labels: approved, cla: yes, lgtm, size/XXL
