Repository istio-ecosystem/authservice, pull requests merged in 2021-03, with the labels that each got.

#136 Add global filter chain configuration API part 2
  docs/README.md
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/service/async_service_impl.cc
  test/filters/filter_chain_test.cc
Labels: approved, cla: yes, lgtm, size/M

#137 Introduce Lazy OIDCConfig validation
  docker-compose.yml
  run/config/config_override.json
  run/envoy/envoy.yaml
  src/config/get_config.cc
  src/config/get_config.h
  src/filters/BUILD
  src/filters/filter_chain.cc
  src/filters/filter_chain.h
  src/main/auth_server.cc
  src/service/async_service_impl.cc
  src/service/async_service_impl.h
  test/config/getconfig_test.cc
  test/filters/filter_chain_test.cc
Labels: approved, cla: yes, lgtm, size/L

#138 Update Dockerfile.
  build/Dockerfile.runner
Labels: approved, cla: yes, lgtm, size/XS
