Repository istio-ecosystem/authservice, pull requests merged in 2022-01, with the labels that each got.

#202 add option to disable remote ca verify
  src/common/http/http.cc
  src/common/http/http.h
  src/filters/oidc/jwks_resolver.cc
  src/filters/oidc/oidc_filter.cc
  test/common/http/mocks.h
  test/filters/oidc/jwks_resolver_test.cc
  test/filters/oidc/oidc_filter_test.cc
Labels: size/L, approved

#203 add option to skip verify peer cert during token endpoint request
  config/oidc/config.proto
  docs/README.md
  src/filters/oidc/jwks_resolver.cc
  src/filters/oidc/jwks_resolver.h
  src/filters/oidc/oidc_filter.cc
  test/filters/oidc/jwks_resolver_test.cc
Labels: size/M, approved

#206 Fix url encoding handling for code parameter.
  Makefile
  src/common/http/http.cc
  test/common/http/http_test.cc
Labels: size/M, lgtm, approved
