Repository istio-ecosystem/authservice, pull requests merged in 2024-04, with the labels that each got.

#243 Allow customizing the Istio version to use in the e2e tests
  e2e/istio/Makefile
  e2e/istio/suite_test.go
Labels: size/M, lgtm, approved

#244 Upgrade Go to 1.22.2 to get rid of CVE-2023-45288
  go.mod
Labels: size/XS, lgtm, approved

#247 Infer the JWS signing algorithm name by looking at the provided key
  internal/authz/oidc.go
  internal/authz/oidc_test.go
Labels: size/M, lgtm, approved

#249 Use the OIDC Discovery end session endpoint if present
  config/gen/go/v1/oidc/config.pb.go
  config/gen/go/v1/oidc/config.pb.validate.go
  config/v1/oidc/config.proto
  e2e/keycloak/authz-config.json
  internal/authz/oidc.go
  internal/authz/oidc_test.go
Labels: lgtm, size/L, approved

#250 Add a logger to log the calls to the Identity Provider
  e2e/istio/istio_test.go
  e2e/keycloak/keycloak_test.go
  e2e/legacy/legacy_test.go
  e2e/testclient.go
  internal/authz/oidc.go
  internal/authz/oidc_test.go
  internal/http/http.go
  internal/http/http_test.go
  internal/http/logging.go
  internal/http/logging_test.go
  internal/logging.go
  internal/logging_test.go
  internal/oidc/jwks.go
  internal/oidc/memory.go
  internal/oidc/redis.go
Labels: lgtm, size/L, approved

#251 Cache well-known responses to avoid making too much calls to the IdP
  internal/authz/oidc_test.go
  internal/oidc/discovery.go
  internal/oidc/discovery_test.go
Labels: size/M, lgtm, approved

#252 Add minimal examples to make it easier to get started
  examples/minimal/authservice-config.yaml
  examples/minimal/authservice.yaml
  examples/minimal/authz-policy.yaml
  examples/minimal/istiod-values.yaml
  examples/minimal/oidc-intercept-policy.yaml
  examples/minimal/rbac.yaml
Labels: lgtm, size/L, approved

#254 Fix scan job configuration
  .github/workflows/scan.yaml
Labels: size/XS, lgtm, approved

#248 Update code owners
  .github/workflows/ci.yaml
  CODEOWNERS
  OWNERS
Labels: size/M, lgtm, approved
