Repository istio-ecosystem/authservice, pull requests merged in 2024-05, with the labels that each got.

#257 Update protoc-gen-go comment to fix `make check`
  config/buf.gen.yaml
  config/gen/go/v1/config.pb.go
  config/gen/go/v1/mock/config.pb.go
  config/gen/go/v1/oidc/config.pb.go
Labels: size/XS

#256 Validate token_type case-insensitively
  internal/authz/oidc.go
  internal/authz/oidc_test.go
Labels: size/S

#258 Fix flaky file watcher test
  internal/file_test.go
Labels: size/L
